southpark-search/app.py, southpark-search/requirements.txt
fix(southpark): fix the requirements
=> fix(southpark): fix the requirements

southpark-search/flow-index.yml, urbandict-search/flow-index.yml
=> fix: reduce the encoder replicas

flower-search/flow-query.yml, southpark-search/flow-query.yml, southpark-search/requirements.txt, urbandict-search/flow-query.yml, urbandict-search/yaml/index-doc.yml
resolves #25 
- fix shards issue in the query flows
- fix the `requirements.txt` in the `southpark` example
- replace the `leveldbIndexer` in the `urbandict` example
=> Fix shards 25

tumblr-gif-search/README.md
=> fix: add docs for shards

flower-search/requirements.txt
fix(flower-search): fixed package dependencies
=> fix(flower-search): fixed package dependencies

flower-search/README.md, flower-search/app.py
fix(flower-search): fixed issue #33
=> fix(flower-search): fixed issue #33

flower-search/README.md
docs(flower-search): updated README.md for issue #33
=> docs(flower-search): updated README.md for issue #33

southpark-search/README.md, southpark-search/flow-query.yml, southpark-search/yaml/index-chunk.yml
- Fixed typos in the doc (jina -> Jina)
- Fixed missing reference for (in Protobuf format) part
- Fixed typos in the code
=> docs(southpark): fix docs and typos in the code

README.md
=> docs(readme): fix hyperlink

flower-search/README.md
Just basic improvements, no restructuring or big changes in this PR
=> examples(flower): fix typos and grammar

pokedex-with-bit/README.md
=> examples(pokedex): correct english, add links

x-as-service/README.md
Just fixing a few types and proposing slight reformulations.
=> Fixing a few typos

flower-search/yaml/craft-load.yml, flower-search/yaml/customized_executors.py
add some missing parts for [PR-93](https://github.com/jina-ai/examples/pull/93)
=> fix: clean up the unless codes

faiss-search/README.md
**Changes introduced**
README.md was cut and it was not complete
=> doc(tests): complete readme docs for faiss search example

faiss-search/flow-index.yml, faiss-search/flow-query.yml, faiss-search/yaml/index-chunk.yml, faiss-search/yaml/index-doc.yml, faiss-search/yaml/query-chunk.yml
**Changes introduced**
Use changes needed to implement issue #98.
use different chunk indexer for indexing and searching. So that we can switch to any 'BaseNumpyIndexer' during search.
=> feat(examples): adapt example to new indexer api with ref indexer

face-db-search/README.md, faiss-search/README.md, flower-search/README.md, helloworld-in-cs/README.md, pokedex-with-bit/README.md, southpark-search/README.md, southpark-search/README.restful.md, tumblr-gif-search/README.md, urbandict-search/README.md, zh/news-search/README.md
=> fix broken url in readme

pokedex-with-bit/README.md, pokedex-with-bit/app.py, pokedex-with-bit/flow-index.yml, pokedex-with-bit/flow-query.yml, pokedex-with-bit/make_html.py, pokedex-with-bit/pods/chunk.yml, pokedex-with-bit/pods/craft.yml
This PR was aligned with issue #116 , migrate Pokemon image search example for Jina 0.4.1 release, includes:
2. Minor changes on Readme.
=> Chore pokedex with bit migrate 116

io-mock-app/app.py, io-mock-app/indexer.yml
part of #116
To test it, please use
```
python app.py index '../**/*.py'
python app.py search
```
where '../\*\*/\*.py' is the glob matching pattern, please change it to where files exist. i.e. /tmp/jina/flower/jpg/\*.jpg for the flower example
=> fix(IoMockApp): migrate

multires-lyrics-search/app.py, multires-lyrics-search/flows/index.yml, multires-lyrics-search/flows/query.yml, multires-lyrics-search/pods/chunk-query.yml, multires-lyrics-search/pods/chunk.yml, multires-lyrics-search/pods/doc.yml
This PR was aligned with issue #116 , migrate multiries search example for Jina 0.4.1 release, includes:
=> Migrate multires lyrics search to jina 0.4.1

flower-search/Dockerfile
=> Fix for #135

multilingual-search/app.py, openapi/python-flask/openapi_server/test/test_doc_controller.py, southpark-search/README.md, southpark-search/app.py, southpark-search/get_data.sh, urbandict-search/README.md, urbandict-search/app.py, zh/news-search/README.md, zh/webqa-search/README.md, zh/webqa-search/app.py
=> change topk to top_k

southpark-search/app.py, southpark-search/pods/encode.yml, southpark-search/pods/text_loader.py
=> fix(southpark): change pooling strategy and fix bug

flower-search/README.md, flower-search/app.py, flower-search/flow-index.yml, flower-search/flow-query.yml
part of #131 , this is not ready to merge yet, will fix the docker image first
=> update flower readme

my-first-jina-app/README.md
After the contents were auto-generated I saw some bugs in my heading levels. This PR fixes this and improves the structure overall
=> Examples: my first app: Heading fixes

multilingual-search/app.py
=> fix: take result from matches chunks

flower-search/README.md
=> docs: clean up english; standardize terms

mnist-with-mindspore/README.md, mnist-with-mindspore/app.py, mnist-with-mindspore/lenet.py, mnist-with-mindspore/mnist-index.yml, mnist-with-mindspore/mnist-query.yml, mnist-with-mindspore/pods/encoder.yml, mnist-with-mindspore/pods/index.yml, mnist-with-mindspore/pods/lenet_mindspore.py, mnist-with-mindspore/pods/load.yml, mnist-with-mindspore/pods/reduce.yml, mnist-with-mindspore/pods/resize.yml, mnist-with-mindspore/requirements.txt
resolved #154 
Basically, this is a duplicate of `jina hello-world`. Instead of `fashionMNIST`, we use `MNIST` together with `LeNet` implemented in `mindspore`.
=> feat: add an example for MNIST with mindspore 154

flow-api-tutorial/README.md
add summarized examples for index and search api
Resolves #134
=> flow api tutorial

faiss-search/README.md
Made several changes in formatting to improve the readability of the FAISS example. Namely,
- removed duplicate table of contents
- fixed grammatical mistakes
- edited for wordiness
- corrected typos
Additionally, I expanded the 'Requirements' section to make it more explicit.
=> Docs edit faiss for clarity and readability

my-first-jina-app/README.md, my-first-jina-app/get_data.sh
* Tweak ordering and wording
* Change `bash` to `source` to ensure env variables set (thanks to @maximilianwerk for that!)
=> fix: update based on latest code and cookiecutter

pokedex-with-bit/pods/doc.yml
=> feat: adapt pokemon search to new recursion strategy

fashion-example-query/fashion/index/indexer-ankleboot.yml, fashion-example-query/fashion/index/indexer-bag.yml, fashion-example-query/fashion/index/indexer-coat.yml, fashion-example-query/fashion/index/indexer-dress.yml, fashion-example-query/fashion/index/indexer-pullover.yml, fashion-example-query/fashion/index/indexer-sandal.yml, fashion-example-query/fashion/index/indexer-shirt.yml, fashion-example-query/fashion/index/indexer-sneaker.yml, fashion-example-query/fashion/index/indexer-trouser.yml, fashion-example-query/fashion/index/indexer-tshirt.yml, fashion-example-query/fashion/index/reduce.yml
=> feat: adapt fashion query language search to new recursion strategy

cross-modal-search/yaml/index-image-kv.yml, cross-modal-search/yaml/index-text.yml
Depending on https://github.com/jina-ai/jina/pull/933
=> feat: adapt cxmodal search to new recursion strategy

southpark-search/pods/index-chunk.yml, southpark-search/requirements.txt
This makes the southpark test easier and works with 0.5.5
=> fix: southpark updated for latest jina

multires-lyrics-search/README.md, multires-lyrics-search/requirements.txt
Clean up, adding missing commands
=> Docs multires fix

multires-lyrics-search/README.md
Kaggle API token information as requested by @JoanFM
=> docs: added kaggle api token information

my-first-jina-app/README.md
Fixes the issue reported in the opening ceremony.
=> fix: update curl command in mfja

pokedex-with-bit/README.md, pokedex-with-bit/app.py, pokedex-with-bit/get_data.sh
* Added `get_data.sh`
* Edited `app.py` to load PNGs from all subdirs
* Added `get_data` stuff to README
=> Feat pokedex get data

tumblr-gif-search/app.py, tumblr-gif-search/craft/craft.yml, tumblr-gif-search/craft/gif2chunk.py, tumblr-gif-search/encode/encode.yml, tumblr-gif-search/flow-index.yml, tumblr-gif-search/flow-query.yml, tumblr-gif-search/index/chunk.yml, tumblr-gif-search/index/doc.yml, tumblr-gif-search/index/rank.yml
I need to look into the details.
There is no error log in indexing and searching. but it couldn't get the result from jinabox, and I need to clean the unnecessary logs.
Resolved #201
=> migrate: tumblrgif example to 0.5

tumblr-gif-search/encode/encode.yml, tumblr-gif-search/index/chunk.yml, tumblr-gif-search/index/doc.yml, tumblr-gif-search/index/rank.yml
=> fix: adapt the config to v0.5.5

tumblr-gif-search/requirements.txt
Can you confirm this is correct @JamesTang-jinaai ? 
resolved #227
=> fix: update jina in requirements

multires-lyrics-search/requirements.txt
fix the broken requirements.txt
=> fix: update the requirements

audio-search/README.md, audio-search/get_data.sh
Script to download samples from [Wikimedia commons](https://commons.wikimedia.org/wiki/Category:WAV_files) (note, just downloads a few of them for testing)
=> feat: data getter script

southpark-search/README.md, southpark-search/app.py
Fixes stupid env variable error and removes chunks from description.
=> fix: renaming env variable. fixing docs

pokedex-with-bit/README.md
Explain how to run outside Docker as well as inside Docker
=> docs(pokedex): explain running outside docker

southpark-search/README.md
small change from previous versions
=> docs: update readme

pokedex-with-bit/README.md, pokedex-with-bit/app.py, pokedex-with-bit/flow-index.yml, pokedex-with-bit/flow-query.yml, pokedex-with-bit/make_html.py, pokedex-with-bit/pods/doc.yml, pokedex-with-bit/pods/vec.yml, pokedex-with-bit/requirements.txt
Once Jina `0.6.4` is released, this PR makes pokedex tree traversal ready.
=> Fix pokedex traversal

multires-lyrics-search/pods/chunk.yml, multires-lyrics-search/pods/doc.yml, multires-lyrics-search/pods/encode.yml, multires-lyrics-search/requirements.txt
Working after jina 0.6.4 relase.
=> fix: lyrics example working with jina 0.6.4

my-first-jina-app/README.md, my-first-jina-app/get_data.sh
This removes the Character names from the my-first-jina-app results.
=> test: small adoption to remove character names

southpark-search/tests/distributed/requirements.txt
Missing thing: run if on jinad master. This needs the completion of code movement from jinad to jina.
=> test: run southpark distributed on jina master

multires-lyrics-search/requirements.txt, multires-lyrics-search/tests/query_results.json, multires-lyrics-search/tests/test_multireslyrics.py
- upgrade multires lyrics example to use jina `0.7.4`
- adapting results
=> test: upgrade multires lyrics to 0.7.4

README.md
Categorization, adding background reading, adding more examples
=> Docs readme revamp

README.md
Fix up wording, capitalization
=> docs(readme): polish wording

southpark-search/tests/distributed/Dockerfile, southpark-search/tests/distributed/test_integration.sh
After this, we can set https://github.com/jina-ai/jina/pull/1218 back to CD and merge it.
=> test: runs with jina and jinad main

southpark-incremental-indexing/README.md, southpark-incremental-indexing/app.py, southpark-incremental-indexing/flow-index.yml, southpark-incremental-indexing/flow-query.yml, southpark-incremental-indexing/get_data.sh, southpark-incremental-indexing/pods/encode.yml, southpark-incremental-indexing/pods/extract.yml, southpark-incremental-indexing/pods/index.yml, southpark-incremental-indexing/pods/index_cache.yml, southpark-incremental-indexing/pods/text_loader.py, southpark-incremental-indexing/prepare_data.py, southpark-incremental-indexing/requirements.txt, southpark-incremental-indexing/tests/data-index-1.csv, southpark-incremental-indexing/tests/data-index-2.csv, southpark-incremental-indexing/tests/test_southparksearch_incremental.py, southpark-search/README.md
Add example of incremental indexing based on South Park
Adapt README
Mention this example as a possible continuation from original South Park.
add integration test
=> test: add incremental indexing example

audio-search/app.py, audio-search/requirements.txt, fashion-example-query/fashion/app.py, fashion-example-query/fashion/requirements.txt
The idea behind this PR is to have code consistency and standards across the modules which is helpful for the users(developers) to understand the code and objective behind it very easily, identify similar patterns and contribute to the open source. Refactored the code in ```fashion-example-query``` and ```audio-search``` module to make it consistent with other modules. Also fixed a minor issue in ```fashion-example-query```.
=> refactor(fashion-audio-search): Code consistency and improvement, fixed "targets" arg in query_generator

multilingual-search/pods/encoder/encode.yml, multilingual-search/pods/encoder/laser_encoder.py
=> Revert "fix: remove laser encoder module"

multires-lyrics-search/app.py
Fixes a bug introduced here: https://github.com/jina-ai/examples/pull/280
=> fix: multires workspace naming

cross-modal-search/README.md
While trying to reproduce the crossmodal example, I noticed some areas of possible improvements / clarifications in the README
=> Docs crossmodal readme formatting

multimodal-search-tirg/README.MD, multimodal-search-tirg/get_data.sh
Add data download script for tirg multimodal example.
=> feat: add download data script

audio-search/Dockerfile, audio-search/download.sh
- fix(audio-search): -t flag on dryrun in Dockerfile
- refactor(audio-search): mv checks to start to error out early, polish prints
=> fix(audio search): dockerfile, download.sh

README.md, example-guidelines.md
- docs: community examples section; guidelines doc
- docs(guidelines): one example per repo
=> docs: community examples

README.md
docs: fix a broken link on README
fixes #340
=> docs: fix a broken link on README

object-search/README.md
This fixes markdown formatting of bash commands: some of them didn't even render properly before
=> fix: fix bash command formatting

multimodal-search-tirg/app.py, multimodal-search-tirg/flow-index.yml, multimodal-search-tirg/flow-query.yml, multimodal-search-tirg/pods/doc.yml, multimodal-search-tirg/pods/merge_matches_sort_topk.yml, multimodal-search-tirg/pods/vec.yml, multimodal-search-tirg/requirements.txt
@bwanglzu ,
once the new Tirg Encoders versions are pushed, could you try that still works with 2 shards?
=> fix: multimodal search make shards possible

.github/workflows/ci.yml, fashion-example-query/tests/test_fashion_example_search.py
This pr intends to add an integration test for fashion example and include in ci.
=> test: add fashion integration test

wikipedia-sentences-incremental/.dockerignore, wikipedia-sentences-incremental/.gitignore, wikipedia-sentences-incremental/Dockerfile, wikipedia-sentences-incremental/README.md, wikipedia-sentences-incremental/app.py, wikipedia-sentences-incremental/data/input-1.txt, wikipedia-sentences-incremental/data/input-2.txt, wikipedia-sentences-incremental/flows/index.yml, wikipedia-sentences-incremental/flows/query.yml, wikipedia-sentences-incremental/manifest.yml, wikipedia-sentences-incremental/pods/encode.yml, wikipedia-sentences-incremental/pods/index.yml, wikipedia-sentences-incremental/pods/index_cache.yml, wikipedia-sentences-incremental/requirements.txt, wikipedia-sentences/README.md
This will replace South Park incremental indexing example
- docs(wikipedia): update readme to use latest docker image on hub
- feat(wikipedia-incremental): initial commit
- docs(wikipedia-incremental): clean up formatting
=> feat add wikipedia incremental

wikipedia-sentences-incremental/README.md, wikipedia-sentences-incremental/app.py, wikipedia-sentences-incremental/pods/index_cache.yml, wikipedia-sentences-incremental/requirements.txt, wikipedia-sentences/app.py, wikipedia-sentences/requirements.txt
Updates wiki examples to latest Jina version
=> Fix wikipedia line format

.github/workflows/ci.yml, audio-search/pods/rank.yml, audio-search/tests/test_audio_search.py, multires-lyrics-search/pods/ranker.yml
Probably we changed the behavior of drivers and meanwhile changed the returned dict.
=> fix: fix failing test

fashion-example-query/Dockerfile, fashion-example-query/requirements.txt
=> chore: bump versions

advanced-vector-search/Dockerfile, advanced-vector-search/requirements.txt
update advanced vector search to 1.0
=> fix: bump the advanced vector search version

pokedex-with-bit/Dockerfile, pokedex-with-bit/requirements.txt, pokedex-with-bit/tests/test_pokedex.py
=> fix: update pokedex example

multimodal-search-tirg/flow-index.yml, multimodal-search-tirg/flow-query.yml, multimodal-search-tirg/requirements.txt
update the multimodal search to 1.0
=> fix: bump the multimodal search version

audio-search/Dockerfile, audio-search/get_data.sh, audio-search/requirements.txt, audio-search/tests/test_audio_search.py
=> fix: fix the audio example

object-search/app.py, object-search/flow-query-object.yml, object-search/flow-query-original.yml, object-search/pods/rank.yml, object-search/requirements.txt
=> fix: update object search

tumblr-gif-search/index/rank.yml, tumblr-gif-search/segment/gif2chunk.py
Issue: https://github.com/jina-ai/examples/issues/429
Reason: https://github.com/jina-ai/jina/pull/2141 
Core solution: https://github.com/jina-ai/jina/pull/2172
=> fix: adapt segmenter for changes

tumblr-gif-search/requirements.txt, tumblr-gif-search/segment/gif2chunk.py
Ref:
https://github.com/jina-ai/jina/issues/2176
https://github.com/jina-ai/jina/pull/2178
Need to wait for the changes of batching are done.
=> fix[tumblr]: adapt single change

audio-search/pods/customized_executors.py, audio-search/requirements.txt
Issue: https://github.com/jina-ai/examples/issues/429
Reason: https://github.com/jina-ai/jina/pull/2141 
Another solution: https://github.com/jina-ai/jina/pull/2172
Ref: 
https://github.com/jina-ai/jina/issues/2176
https://github.com/jina-ai/jina/pull/2178
Need to wait for the changes of batching are done.
=> fix[audio]: adapt segmenter for changes

advanced-vector-search/tests/conftest.py, audio-search/tests/conftest.py, multires-lyrics-search/tests/conftest.py, object-search/tests/conftest.py, pokedex-with-bit/tests/conftest.py, tumblr-gif-search/tests/conftest.py, wikipedia-sentences/tests/conftest.py
=> test: add conftest

chinese-text-search/README.md, chinese-text-search/app.py, chinese-text-search/flows/index.yml, chinese-text-search/flows/query.yml, chinese-text-search/requirements.txt
- update Jina to 1.1.0 (if not already at that version or higher)
- modify flow yamls to enable REST API
- add index_rest method that indexes docs using the /index REST API
- add index_rest as CLI option to -t (via click options)
- change README to point towards /search (NOT /api/search)
=> fix: chinese text eg using CRUD REST

tumblr-gif-search/README.md, tumblr-gif-search/app.py, tumblr-gif-search/flow-index.yml, tumblr-gif-search/flow-query.yml, tumblr-gif-search/requirements.txt
update Jina to 1.1.0
add index_rest that indexes docs using the /index REST API
add index_rest to click options
=> fix: tumblr search using CRUD REST

.github/workflows/ci.yml
Add paths to latest examples for updating ci
=> Update ci.yml paths

.gitignore, advanced-vector-search/yaml/custom_executors.py, audio-search/pods/customized_executors.py, fashion-example-query/components.py, fashion-example-query/tests/test_fashion_example_search.py
Solves: https://github.com/jina-ai/examples/issues/478
=> Fix executor signature

cross-modal-search/README.md, cross-modal-search/app.py, cross-modal-search/flow-index.yml, cross-modal-search/flow-query.yml, cross-modal-search/requirements.txt
update Jina to 1.1.0
add index_rest that indexes docs using the /index REST API
add index_rest to click options
=> fix: cross modal eg using CRUD REST

multires-lyrics-search/README.md, multires-lyrics-search/app.py, multires-lyrics-search/flows/index.yml, multires-lyrics-search/flows/query.yml, multires-lyrics-search/requirements.txt
update Jina to 1.1.0
add index_rest that indexes docs using the /index REST API
add index_rest to click options
=> fix: multires using CRUD REST

.github/ci.sh, .github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/copyright.yml, cross-modal-search/Dockerfile, multires-lyrics-search/Dockerfile, multires-lyrics-search/tests/conftest.py, object-search/Dockerfile
Move to dependabot, to reflect changes in Hub
=> ci: move to dependabot

audio-search/app.py, audio-search/flows/index.yml, audio-search/flows/query.yml, audio-search/pods/customized_executors.py, audio-search/requirements.txt
update Jina to 1.1.0 (if not already at that version or higher)
add index_rest method that indexes docs using the /index REST API
add index_rest as CLI option to -t (via click options)
=> fix: audio search eg using CRUD REST

wikipedia-sentences/README.md
Adding and fixing links for Wikipedia Examples
Removing irrelevant links
=> fix: update links for wikipedia

object-search/requirements.txt
As a user, I would expect all the libraries I need to be in the requirements.txt file.
=> feat: add kaggle library

object-search/app.py
Fix a bug that was preventing indexing.
Also moved the logic for checking the workspace to before the actual task calls.
=> fix: obj search ws

wikipedia-sentences/README.md, wikipedia-sentences/get_data.sh
Removed shuf command since it doesn't exist on Mac. 
Alex, please let me know if you think the new logic in the data file is okay!
=> fix: remove shuf command 

example_template.md
Includes
- @alexcg1 changes of typos and links
- @aga11313 changes to the structure and verbosity of the example
=> fix: template tweaks

cross-modal-search/README.md, cross-modal-search/app.py
- Fix `cross modal` search for `num_docs` and `request size`
=> fix: cross modal example

multires-lyrics-search/README.md, multires-lyrics-search/app.py
=> fix: multires lyrics

object-search/Dockerfile, object-search/requirements.txt
=> fix: add hub requirements

advanced-vector-search/Dockerfile, advanced-vector-search/app.py, advanced-vector-search/flow-index.yml, advanced-vector-search/flow-query.yml, advanced-vector-search/manifest.yml, advanced-vector-search/requirements.txt, advanced-vector-search/tests/test_advanced_vectors_search.py
fix advanced vector search for 1.2
=> fix advanced vector search for 1.2

fashion-example-query/app.py, fashion-example-query/requirements.txt
this fixes a couple of issues in the fashion example and upgrades Jina there to 1.1
With this PR it runs, although precision/recall values dont work. (evaluations are empty)
=> fix fashion example query

object-search/app.py
Refactoring prints to logger
Refactoring structure of code (around workspace-checking)
=> refactor: logging and restructure workspace cleaning

.github/ci.sh
Closes https://github.com/jina-ai/examples/issues/557
=> fix: use separate venvs

object-search/README.md
closes https://github.com/jina-ai/examples/issues/519
=> feat: add ref to lib-magic

multires-lyrics-search/README.md
Hi @aga11313 @alexcg1 
If you guys could review this and let me know what you think? Especially the section about explaining the results..I'm very interested to hear if that makes sense to anyone else.
=> feat: add new template

multimodal-search-pdf/Dockerfile, multimodal-search-pdf/README.md, multimodal-search-pdf/app.py, multimodal-search-pdf/pods/rankc.yml, multimodal-search-pdf/requirements.txt, multimodal-search-pdf/tests/test_pdfsearch.py
=> update the pdf search example to 1.2

audio-search/Dockerfile, audio-search/README.md, audio-search/app.py, audio-search/flows/index.yml, audio-search/flows/query.yml, audio-search/requirements.txt, audio-search/tests/test_audio_search.py
=> update the audio search example to 1.2

.github/workflows/ci.yml
=> fix: add py3-8 for testing

object-search/README.md, object-search/app.py, object-search/flow-index.yml, object-search/requirements.txt, object-search/tests/test_objectsearch.py
=> update object-search to 1.2

wikipedia-sentences/README.md
as per comment in PR https://github.com/jina-ai/examples/pull/578#discussion_r631120213
=> test: if doctoc works

example_template.md
Some minor improvements from other PRs
=> feat: minor improvements

tumblr-gif-search/README.md
add notice if the index hangs.
=> fix: add trouble shooting hints for tumblr

cross-modal-search/README.md, cross-modal-search/app.py, cross-modal-search/requirements.txt
1. add hints to readme if index hangs.
2. reduce the default `request_size`  parameter, from 16 to 12.
3. downgrade jina to 1.1.5, to temporarily fix issue described [here](https://github.com/jina-ai/jina/issues/2202#issuecomment-843117878)
=> feat: add hang trouble shooting

wikipedia-sentences/flows/index.yml, wikipedia-sentences/flows/index_incremental.yml, wikipedia-sentences/flows/query.yml, wikipedia-sentences/pods/encode.yml, wikipedia-sentences/pods/index.yml, wikipedia-sentences/pods/index_cache.yml
Relates to #445 
I have added comments to the yaml files in the wikipedia-sentences example.
The example is still based on jina 1.2.0.
=> docs: wikipedia yaml comments

cross-modal-search/Dockerfile, cross-modal-search/README.md, cross-modal-search/app.py, cross-modal-search/evaluate.py, cross-modal-search/flow-index.yml, cross-modal-search/flow-query.yml, cross-modal-search/requirements.txt, cross-modal-search/yaml/image-normalize.yml
update cross modal search to 1.2
=> update cross modal search to 1.2

advanced-vector-search/requirements.txt, audio-search/requirements.txt, chinese-text-search/requirements.txt, fashion-example-query/requirements.txt, multimodal-search-pdf/app.py, multires-lyrics-search/requirements.txt, object-search/requirements.txt, pokedex-with-bit/requirements.txt, tumblr-gif-search/requirements.txt, wikipedia-sentences-query-while-indexing/requirements.txt, wikipedia-sentences/requirements.txt
fix the ci using git instead of pypi
=> fix the ci using git instead of pypi

multimodal-search-tirg/flow-index.yml, multimodal-search-tirg/flow-query.yml, multimodal-search-tirg/requirements.txt
feat: update multi-modal-search to 1.2
=> feat: update multi-modal-search to 1.2

multimodal-search-pdf/requirements.txt
fix: fix the pip installation issues
=> fix: fix the pip installation issues

.github/dependabot.yml
=> fix: ignore patch updates

cross-modal-search/app.py, cross-modal-search/flows/flow-index.yml, cross-modal-search/flows/flow-query.yml, cross-modal-search/pods/executors.py, cross-modal-search/pods/index-text.yml, cross-modal-search/pods/merge_matches_sort_topk.yml
help to adapt the cross modal search to 2.0
=> help to adapt the cross modal search to 2.0

cross-modal-search/app.py, cross-modal-search/flows/flow-index.yml, cross-modal-search/flows/flow-query.yml, cross-modal-search/pods/clip/image-encoder.yml, cross-modal-search/pods/executors.py
switch to use hubble images for the crossmodal search example
=> feat: switch to use hubble images

multimodal-search-pdf/flows/executors.py
I remember we will not keep this example after 2.0 official release right? @slettner
=> fix: fix error

README.md
closes https://github.com/jina-ai/jina/issues/2872
=> Chore update metrics section

README.md
Removed dead example links. [Reference](https://jinaai.slack.com/archives/C018NC4SYAZ/p1626617965089700)
=> docs(readme): rm image search, pdf search

README.md
remove performance metrics section
=> docs: remove performance metrics section

cross-modal-search/Dockerfile, cross-modal-search/pods/executors.py, cross-modal-search/requirements.txt
This PR optimizes the Dockerfile in cross-modal-search example and closes issue #685. Thanks.
=> feat: optimize Dockerfile in cross-modal-search and fixes #685

cross-modal-search/README.md, example_template.md, multires-lyrics-search/README.md, wikipedia-sentences-query-while-indexing/README.md
Fixes [this issue](https://jina-ai.slack.com/archives/C0169V26ATY/p1627652167011500)
=> fix: fix all slack links

cross-modal-search/dataset.py
I believe this PR fixes the issue #700
=> fixed the issue #700

wikipedia-sentences/README.md
=> docs(readme): fix wikipedia sentences readme guide

cross-modal-search/flows/flow-query.yml
fix the bugs in crossmodal search
When https://github.com/jina-ai/jina/pull/3472 is merged, this can be reverted.
=> fix: fix the bugs in crossmodal search
