urbandict-search/README.md, urbandict-search/flow-query.yml, urbandict-search/http_query.py
This illustrates, that using the jina `py_client` is seamless and works identical to querying a local flow directly.
I append it to an existing example, since it is a bit to small of a learning to create a new tutorial. Fixing the port in the querying flow happens in order to not get confused by the random port selection of jina.
This should solve [358](https://github.com/jina-ai/jina/issues/358)
=> docs(py_client): added usage of py_client to urbandict

face-db-search/yaml/craft-load.yml, face-db-search/yaml/customized_executors.py, face-db-search/yaml/index-doc.yml, flower-search/app.py, flower-search/yaml/craft-load.yml, flower-search/yaml/customized_executors.py, flower-search/yaml/index-doc.yml
PR implementing proposal from #620. Linked PR in jina core: https://github.com/jina-ai/jina/pull/627
**Changes introduced**
- ImageReader should work together with a Segmenter inside a CompoundExecutor
- Correct DocDriver level
- Fix flower search app.py to send image buffer and not the uri in the buffer
=> feat(examples): add crafter as compound executor

flower-search/app.py, flower-search/yaml/craft-load.yml
Running flower example shows an error:
jina.excepts.UnattachedDriver: <jina.drivers.craft.DocCraftDriver object at 0x7f53ad9df2b0>,
probably because the !CompoundExecutor only has one component.
This PR fixed it accordingly and add batch_size.
=> fix(flower): fix problems

face-db-search/Encoder/Dockerfile, face-db-search/README.md, face-db-search/app.py, face-db-search/flow-index.yml, face-db-search/flow-query.yml, face-db-search/make_html.py, face-db-search/yaml/craft-flip.yml, face-db-search/yaml/craft-load.yml, face-db-search/yaml/craft-normalize.yml, face-db-search/yaml/customized_executors.py, face-db-search/yaml/index-chunk.yml, face-db-search/yaml/index-doc.yml
This PR was aligned with issue #116 , migrate face db search example for Jina 0.4.1 release, includes:
1. Code migration based on [migration guide](https://github.com/jina-ai/jina/issues/702).
2. Minor refactoring to replace `SegmentDriver` with `CraftDriver` in `yaml/craft_load`, to make the example work.
3. Some minor changes on Readme.
Apart from this, while debugging `make_html.py`, `match.meta_info` gives me an empty buffer, might need to update `jina`. Please see attached image blow.
@JoanFM Spent a lot of time helping me walking through this process, special thanks to him!
=> Migrate face db search example to Jina 0.4.1

urbandict-search/app.py, urbandict-search/flow-query.yml, urbandict-search/yaml/craft-split.yml, urbandict-search/yaml/encode.yml, urbandict-search/yaml/index-doc.yml, urbandict-search/yaml/query-craft.yml, urbandict-search/yaml/splitter.py
Hey @YueLiu-jina .
This is the idea I had, it is now broken due to a problem in `transformers` when dealing with different lengths of tokens.
The idea is that here we have the `word` and the set of `definitions`. The word does not have to be `encoded`, therefore I add a splitter before the `sentencizer` to extract the word and set it as `meta_info`, so that later we can say. The closest word to the `definition given` is the one extracted from the `doc.matches[idx].meta_info.decode()`.
Does this sound like a good idea @nan-wang?
If the aim of the example is to search for `words` given a `definition`, the word itself should not be encoded.
Now it works if the versions required by https://github.com/jina-ai/jina/issues/753 are used.
I understand the flow. We are using the closest definition …
=> fix(urbandict): add splitter

x-as-service/README.md, x-as-service/app.py
This PR was aligned with issue #116 , migrate x-as-service  example for Jina 0.4.1 release, includes:
2. Minor changes on Readme.
To run this example, you should build pytorch-transformer image locally using jina 0.4.1 with Dockerfile:
```docker
FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime
RUN pip install transformers --no-cache-dir --compile && \
python -c "from transformers import *; x='bert-base-uncased'; BertModel.from_pretrained(x); BertTokenizer.from_pretrained(x)"
RUN pip install git+https://github.com/jina-ai/jina.git/@master
ENTRYPOINT ["jina", "pod", "--uses", "TransformerTorchEncoder"]
```
And command:
```python
docker build -f Dockerfile -t jinaai/hub.executors.encoders.nlp.transformers-pytorch .
```
=> Migrate x-as-service to jina 0.4.1

multilingual-search/app.py, multilingual-search/flow-index.yml, multilingual-search/flow-query.yml, multilingual-search/pods/chunk_indexer/index-chunk.yml, multilingual-search/pods/doc_indexer/index-doc.yml
This PR was aligned with issue #116 , migrate multilingual search example for Jina 0.4.1 release, includes:
Need to be noted that this example do not have a readme file.
=> Migrate multilingual search to jina 0.4.1

multires-lyrics-search/app.py, multires-lyrics-search/flows/index.yml, multires-lyrics-search/flows/query.yml, multires-lyrics-search/pods/chunk-query.yml, multires-lyrics-search/pods/chunk.yml, multires-lyrics-search/pods/doc.yml, tumblr-gif-search/README.md, tumblr-gif-search/app.py, tumblr-gif-search/craft/craft.yml, tumblr-gif-search/flow-index.yml, tumblr-gif-search/flow-query.yml, tumblr-gif-search/index/chunk.yml
This PR was aligned with issue #116 , migrate tumblr search example for Jina 0.4.1 release, includes:
2. Minor changes on Readme.
Note, the script `gif_download.py` might cause an exception while downloading gifs, something needs to be investigate further more later.
=> Migrate tumplr gif search to jina 0.4.1

southpark-search/app.py, southpark-search/flow-index.yml
Small refactor for `southpark` waiting to have the fix for `urbandict` (@nan-wang) to replicate in this example.
Next steps:
=> refactor: small southpark refactor

faiss-search/flow-query.yml, faiss-search/yaml/indexer.yml
For structures like this, it would be necessary (imagine here we would use NumpyIndexer at query time) to have the change in 
https://github.com/jina-ai/jina/pull/870
=> refactor: remove ranker is not necessary

my-first-jina-app/README.md
I'd left the old git repo in the README. I've corrected it to download the examples repo instead so user always has latest version of the tutorial and associated files
Fixes #170 
Note: After discussion with team, there's consensus to fix cookiecutter, therefore this example can be brought back from the dead. Hence me pushing the fix
=> fix(my-first-jina-app): correct git repo

face-db-search/yaml/index-chunk.yml, flower-search/yaml/index-chunk.yml, mnist-with-mindspore/pods/index.yml, southpark-search/README.md, southpark-search/pods/index-chunk.yml, zh/news-search/pods/chunk_indexer/chunk_indexer.yml, zh/webqa-search/README.md, zh/webqa-search/pods/chunk_indexer/chunk_indexer.yml
- Changed `metrix` to `metric` in all relevant examples - fixes typo.
=> fix: change metrix to metric

southpark-search/README.md, southpark-search/pods/index-chunk.yml, southpark-search/requirements.txt
This should make the example run for jina 0.5.4. The changes can be reverted, once 0.5.5 is published.
=> fix: running for current latest jina

multires-lyrics-search/README.md
Removed, since it is broken. If I can fix it today, I'll add it back in.
=> fix: remove docker from lyrics for now

my-first-jina-app/README.md
Changing `DATA_PATH` to `JINA_DATA_PATH`, adding `jina_version` option for CLI on running `cookiecutter`.
=> fix: updating MFJA README with new env variables

tumblr-gif-search/README.md
Fix Python commands, for example `python app.py index` instead of `python app.py`
=> fix: correct python commands

southpark-search/app.py
During the Hackaton a lot of people run the query and index commands in the wrong order or indexed twice and got errors. That should prevent it.
=> feat: better error detection regarding workspace

southpark-search/flow-index.yml, southpark-search/flow-query.yml, southpark-search/pods/index-doc.yml, southpark-search/pods/index.yml
Adapting the example for `traversal_paths` implementation.
On the way making the example really slim, since there weren't any chunks, no chunk indexing is needed. Anyhow, that quality was better with jina `0.5.5` and I don't know why.
=> fix: southpark working again

fashion-example-query/fashion/app.py, fashion-example-query/fashion/index/indexer-ankleboot.yml, fashion-example-query/fashion/index/indexer-bag.yml, fashion-example-query/fashion/index/indexer-coat.yml, fashion-example-query/fashion/index/indexer-dress.yml, fashion-example-query/fashion/index/indexer-pullover.yml, fashion-example-query/fashion/index/indexer-sandal.yml, fashion-example-query/fashion/index/indexer-shirt.yml, fashion-example-query/fashion/index/indexer-sneaker.yml, fashion-example-query/fashion/index/indexer-trouser.yml, fashion-example-query/fashion/index/indexer-tshirt.yml, fashion-example-query/fashion/index/reduce.yml, fashion-example-query/fashion/requirements.txt
This will fix the fashion-example, once jina `0.6.4` is released.
=> fix: fashion example traversal tree ready

README.md
Currently the email link points to an email address, I assume it would be better to point directly to mailchimp signup as the main website does?
=> Fix: Email newsletter link

southpark-search/tests/test_southparksearch.py
Some refactoring of the test:
- constants should be upper cased
- there is no need to use `getattr` here and make code complicated
- use pytest native `tmpdir` fixture
=> refactor: adapted tests to the jina style of testing

southpark-search/tests/distributed/docker-compose.yml
removed the linking, since it automatically happens by container name in latest docker-version. `links` is deprecated by docker-compose.
=> fix: made docker-compose file slimmer

multires-lyrics-search/requirements.txt
There is a new version (`4.0.0`) of `transformers` release which breaks our current interface to transformers. thus, I fixed the version to `3.5.1`.
=> fix: transformers version in lyrics fixed

flower-search/get_data.sh
updated url for 17flowers data set. Otherwise get_data fails.
UPD:
The old URL works, but it downloads a redirect page, then tar command fails.
```
$ curl http://www.robots.ox.ac.uk/~vgg/data/flowers/17/17flowers.tgz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.robots.ox.ac.uk/~vgg/data/flowers/17/17flowers.tgz">here</a>.</p>
</body></html>
```
=> fix(flower-search): updated url for 17flowers data set

my-first-jina-app/README.md
There was $ sign for exporting a variable which wasn't required
=> fixed typo in the Readme file for my-first-app

README.md
Based on results of discussions, I've cut many examples from the readme and re-organized. Also general tidying up and structuring
- docs(readme): slim down, revamp into simple-advanced
- docs(readme): modality emoji
- docs(readme): table test
- docs(readme): table fix
- docs(readme): table style
- docs(readme): simple example table done
- docs(readme): advanced/docs tables done
- docs(readme): emojis, reorder, fix doc bullets
- docs(readme): condense 101, what is neural search; replace docs table with link; clearer headings
=> docs: examples readme overhaul

.gitignore
Some examples use scripts to download their model (like audio search). We shouldn't upload those to our repo.
=> fix: ignore dirs for models downloaded via script

advanced-vector-search/requirements.txt
Added docker to requirements.txt to enable the usage of annoy or faiss from their docker images.
=> fix: add docker to requirements.txt

advanced-vector-search/Dockerfile, advanced-vector-search/README.md, advanced-vector-search/app.py, advanced-vector-search/flow-index.yml, advanced-vector-search/flow-query.yml, advanced-vector-search/generate_training_data.py, advanced-vector-search/get_data.sh, advanced-vector-search/get_siftsmall.sh, advanced-vector-search/read_vectors_files.py, advanced-vector-search/requirements.txt, advanced-vector-search/tests/test_advanced_vectors_search.py, advanced-vector-search/yaml/annoy-indexer.yml, advanced-vector-search/yaml/faiss-indexer.yml, advanced-vector-search/yaml/hub-annoy-indexer.yml, advanced-vector-search/yaml/hub-faiss-indexer.yml, advanced-vector-search/yaml/indexer.yml, advanced-vector-search/yaml/merge-matches-sort.yml
**Changes introduced**
- Adapt to latest changes in `workspace` configurations
- Adapt scripts to use `sift` and `siftsmall`
- Prepare dockerfile for `sift`
- Parametrize the `Faiss` and `Annoy` Indexers parameters so that the user can tweak them when using the docker image
**TODO**
=> refactor: prepare example to host 1M docs

audio-search/README.md, audio-search/download_data.sh
In the audio-search example, while downloading data, an external git repository is cloned and its code is used.
From this external module [ https://github.com/qiuqiangkong/audioset_tagging_cnn.git ] the python script [./utils/dataset.py] is launched. This script includes an hardcoded os.command to youtube-dl and ffmpeg.
These two dependencies are not part of any default unix distro, but they are not listed in any requirements file as well.
This PR includes:
- a check for the commands' existence inside the data download script
- an error message in case the dependencies are not found, with an install suggestion
- the update of the README file, in order to advice the user of the dependencies
=> [BUG][FIX] Add dependency check and warning messages

cross-modal-search/README.md
The provided `download_data_kaggle.sh` is missing instructions to create the `data` folder and the `f8k` folder.
=> fix: add  mkdir instructions

.github/workflows/ci.yml
Other test jobs will be canceled once one test fails. So adding fail-fast: false can help us find out other failing tests.
=> ci: set fail-fast false

object-search/README.md
Proposed changes include:
- Add link to COCO dataset.
- Add an empty line to fix formatting syntax error. Without this line, the string **original** will not be displayed correctly.
=> fix: add link to COCO dataset and fix formatting syntax error

.github/workflows/ci.yml, object-search/Dockerfile, object-search/README.md, object-search/flow-index.yml, object-search/flow-query-object.yml, object-search/pods/rank.yml, object-search/requirements.txt, object-search/tests/test_objectsearch.py
Since Minranker is removed, 'search original' cannot work.
And in Jina==1.0.4 when do indexing, `AttributeError: meta_info is not recognized` occurs.
=> fix: update object-search requirements

tumblr-gif-search/index/rank.yml
tumblr is failing because we need to adapt bimatch ranker to change 'length' to 'weight' or use other ways of implementation.
This is a PR to demo a workaround for this example.(replace the ranker).
But I prefer to use different rankers in our examples.
=> fix[tumblr]: change ranker

.gitignore, README.md, advanced-vector-search/app.py, advanced-vector-search/metrics.txt, advanced-vector-search/requirements.txt, advanced-vector-search/setup_run.sh, advanced-vector-search/tests/test_advanced_vectors_search.py, audio-search/app.py, audio-search/setup_run.sh, perf-script.sh, performance.txt
Add script to run and gather timing information from all examples.
NOTE - only done for adv indexers case, as an example of how it would look like. Pending feedback, should be implemented by all
=> feat: add timing script

wikipedia-sentences/README.md, wikipedia-sentences/app.py, wikipedia-sentences/flows/index.yml, wikipedia-sentences/flows/query.yml, wikipedia-sentences/requirements.txt
- update Jina to `1.1.0`
- modify flow yamls to enable REST API
- add index_rest that indexes docs using the `/index` REST API
- add index_rest to click options
- change README to point towards `/search` (NOT `/api/search`)
=> refactor: wiki ex uses REST for CRUD

advanced-vector-search/app.py, advanced-vector-search/flow-index.yml, advanced-vector-search/flow-query.yml, advanced-vector-search/requirements.txt, advanced-vector-search/tests/test_advanced_vectors_search.py, advanced-vector-search/yaml/custom_executors.py
update Jina to 1.1.0 (if not already at that version or higher)
add index_rest method that indexes docs using the /index REST API
add index_rest as CLI option to -t (via click options)
=> fix: adv vector search eg using CRUD REST

object-search/README.md, object-search/app.py, object-search/flow-index.yml, object-search/flow-query-object.yml, object-search/flow-query-original.yml, object-search/requirements.txt
update Jina to 1.1.0
add index_rest that indexes docs using the /index REST API
add index_rest to click options
=> fix: object search using CRUD REST

.github/workflows/ci.yml
This closes https://github.com/jina-ai/examples/issues/536
The CI change itself should not be tested as part for this PR, but I've created a dummy PR where one can see that S3 access works with those credentials added here: https://github.com/jina-ai/examples/pull/539/files
=> feat: add aws access in ci

perf-script.sh, util/pull_dataset.py
Use the new version of `jinacld_tools` (used for pulling datasets from S3).
=> chore: update jinacld version

multimodal-search-pdf/README.md
Some people reported that cloning examples take time, so now I have added quick commands to copy only one example instead of all of them
=> Added commands to speed up cloning using sparse checkout

.github/ci.sh, advanced-vector-search/requirements.txt, advanced-vector-search/tests/requirements.txt, audio-search/requirements.txt, audio-search/tests/requirements.txt, chinese-text-search/requirements.txt, cross-modal-search/requirements.txt, fashion-example-query/requirements.txt, fashion-example-query/tests/requirements.txt, multimodal-search-pdf/requirements.txt, multimodal-search-pdf/tests/requirements.txt, multimodal-search-tirg/requirements.txt, multires-lyrics-search/requirements.txt, multires-lyrics-search/tests/requirements.txt, object-search/requirements.txt, object-search/tests/requirements.txt, pokedex-with-bit/requirements.txt, pokedex-with-bit/tests/requirements.txt, templates/nlp-simple/tests/requirements.txt, tumblr-gif-search/requirements.txt, tumblr-gif-search/tests/requirements.txt, wikipedia-sentences-query-while-indexing/requirements.txt, wikipedia-sentences-query-while-indexing/tests/requirements.txt, wikipedia-sentences/requirements.txt, wikipedia-sentences/tests/requirements.txt
Fixes https://github.com/jina-ai/internal-tasks/issues/86
At present, anything installed from `requirements.txt` in examples repo is not tracked by pypi, so we can't get those metrics. But do we even want those numbers?
- If it's our CI doing that, we DON'T want those numbers. 
- If it's our users, we DO want those numbers. 
This PR creates a separate requirements.txt in each example's `test/` directory, and tells our CI to install from that. 
It reverts `./requirements.txt` to installing from pypi, which is what real users would do.
- test: separate reqs for users and ci. users install direct
- test: set ci to install requirements.txt from test dir
=> fix pip numbers leakage

README.md
Only removed from the README, not from the repo itself.
This PR:
- Removes references to examples that have not (and will not) be updated for 2.0 - [see thread on Slack](https://jinaai.slack.com/archives/C018NC4SYAZ/p1624371433051700)
- Updates intro for 2.0
- Adds @alexcg1's community examples (meme and app search)
- docs(readme): switch to 2.0 content, rm dead links
- docs(readme): remove links to examples on deathlist or not updated for 2.0
- docs(readme): add @alexcg1's community examples
=> docs(readme): remove unused and unusable examples

cross-modal-search/app.py, cross-modal-search/flows/flow-index.yml, cross-modal-search/flows/flow-query.yml, cross-modal-search/pods/clip/image-encoder.yml, cross-modal-search/pods/executors.py, cross-modal-search/requirements.txt
The fix temporarily reverts previous change that ports CLIPEncoder to Jinahub because a hang occurs. Also remove the lines `f.use_rest_gatway()` as the function is now removed.
=> fix: temporary fix for cross-modal-search index flow to work on Jina 2.0

cross-modal-search/Dockerfile, cross-modal-search/flows/flow-index.yml, cross-modal-search/flows/flow-query.yml, cross-modal-search/pods/executors.py, cross-modal-search/requirements.txt
This PR bumps the Jina version of cross-modal-search to 2.0.4 and port ImageNormalizer and CLIPImageEncoder to use jinahub+docker
=> fix: bump Jina version and Port ImageNormalizer and CLIPImageEncoder to use jinahub+docker

.github/ci.sh, wikipedia-sentences-query-while-indexing/README.md, wikipedia-sentences-query-while-indexing/requirements.txt, wikipedia-sentences-query-while-indexing/tests/requirements.txt
Instead of using `master-daemon` image for JinaD, this PR changes both jina version & jinad docker image version to `2.1.0`.
=> chore(qwi): update to 2.1.0

README.md
[get started](https://github.com/jina-ai/examples/blame/master/README.md#L18) in README is pointing to https://github.com/jina-ai/jina/#get-started which doesn't exist. 
I updated it to https://github.com/jina-ai/jina/#build-your-first-jina-app
=> updated the Get started link in README.md
